### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by andys8** [lukewestby/elm-http-builder#22]
Updating the changelog would be nice. Looks like it is out of sync right now.
## Releases
![screenshot_20180905-235003](https://user-images.githubusercontent.com/13085980/45125493-a3577b00-b166-11e8-9208-f743a2f752ab.png)

## Changelog
![screenshot_20180905-234942](https://user-images.githubusercontent.com/13085980/45125497-a9e5f280-b166-11e8-8475-ef4ce870c59d.png)

Thanks :+1:

**Comment by lukewestby** [comment]
@andys8 i'm not gonna have time to do this. if you want to submit a pr i'll be happy to merge it. thanks!
