### ISSUE TITLE
Upgrade to elm/http 2.0.0

### ISSUE THREAD

**Issue by Natim** [lukewestby/elm-http-builder#23]

**Comment by lukewestby** [comment]
hey @Natim, sorry this is holding up your upgrade for the kinto client. i'm still working out how the api will change. if you have input i'd be happy to hear it

**Comment by Natim** [comment]
Don't worry too much about it :) I will ping @magopian and @n1k0 who might have insights too.

**Comment by Natim** [comment]
To be honest I really like the way it currently is :joy:

**Comment by absynce** [comment]
Is the API discussion for this going on anywhere? I imagine this upgrade will have some important implications on the API. 

Motivation: I'm looking into upgrading a client project to elm/http 2.0.0.

**Comment by kornicameister** [comment]
Same motivation. I find default API of `elm/http` somehow crude. Have been using this library always with `elm/http<2.0.0` and it as convenient as `elm-json-pipeline`. If there's some help needed, perhaps we can help.

**Comment by lukewestby** [comment]
Hey folks, I would actually love a PR for this. I’ve been overloaded recently with personal stuff and getting the elm-conf cfp started. If you want any kind of guidance just @ me in a review comment

**Comment by kornicameister** [comment]
@lukewestby there is a PR already https://github.com/lukewestby/elm-http-builder/pull/25 :)

**Comment by lukewestby** [comment]
alright folks, this is done. sorry for the wait. i'm gonna find someone to take over maintaining this package so it doesn't happen again
