### ISSUE TITLE
Should withJsonBody set the content-type header?

### ISSUE THREAD

**Issue by arsduo** [lukewestby/elm-http-builder#29]
I just ran into an issue that was briefly confusing -- setting a JSON body doesn't also set the request to "Content-Type" "application/json". I can't imagine a common situations where you'd use a JSON body without also setting that header -- would it make sense to have the library do both at once? 

If that sounds like a good change I can submit a PR.

**Comment by arsduo** [comment]
Actually, even setting that doesn't seem to be enough to get Rails to recognize the request as JSON, so this isn't an urgent issue. Might still be worth doing, though.

**Comment by lukewestby** [comment]
Hey @arsduo! elm/http is _supposed_ to set the Content-Type header automatically based on the body used so if you are seeing requests that use withJsonBody go out where that header isn't set to application/json then I would need a small example to reproduce the issue.

Something I have had to do with Rails to get it to recognize the request is set a custom header `X-Requested-With: XMLHttpRequest`. That header value apparently has some magical meaning within Rails.

Anyway, if you can reproduce the issue with a small example let me know and then I'd love a pull request for a workaround if you can find one.
