### ISSUE TITLE
Make send's readers a list?

### ISSUE THREAD

**Issue by canadaduane** [lukewestby/elm-http-builder#3]
It feels clunky to me to always pass two readers (jsonReader, stringReader) to `send`. Would it make sense to turn it into a list of readers, sorted in order of preference? I can imagine an xmlReader. Possibly a yamlReader.

**Comment by lukewestby** [comment]
We would still need two separate lists of readers to handle both the error and the success cases since we're dealing with Tasks. In the example you mentioned, the `jsonReader` is handling 20x cases and the `stringReader` is handling everything else.

**Comment by canadaduane** [comment]
Ah, I misunderstood how that works. I thought I was reading a fallback in case there was an error, not a case where the error resulted in a differently-typed response (i.e. a string instead of json).
