### ISSUE TITLE
withFileZeroStatusAllowed shouldn't explicitly test for file:// protocol in response.url

### ISSUE THREAD

**Issue by ccapndave** [lukewestby/elm-http-builder#4]
I'm not quite sure why this is, but testing shows that this test fails with Cordova on iOS, causing a `BadResponse` error even with zero status.  I'm not sure if `response.url` is unavailable, or if `file://` masquerades as `http://` under some circumstances (possibly when using service workers), but anyway it definitely doesn't work :)

Perhaps it would be an idea to change the method name to simply `withZeroStatusAllowed` to clarify that its not restricted to the `file://` protocol.

**Comment by lukewestby** [comment]
yep, this sounds good. wanna submit a pr?

**Comment by ccapndave** [comment]
Sure thing - I'll do it today
